DEEPSORT:
  REID_CKPT: "./deep_sort/deep/checkpoint/padded_aug.t7"
  NUM_CLASSES: 43
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  APPLY_PAD: True
